project:
  name: quickstart-aws-vpc
  owner: quickstart@amazon.com
  package_lambda: false
  template: templates/role.yaml
  regions:
    - eu-central-1
test-scenario-1:
    regions:
    - eu-central-1
