project:
  name: quickstart-aws-iam
  owner: quickstart@amazon.com
  package_lambda: false
  template: templates/role.yaml
  regions:
    - eu-central-1
tests:
  test-scenario-1-with-role:
      parameters:
        CreateRole: "true"
      regions:
      - eu-central-1
  test-scenario-2-with-user:
      parameters:
        CreateUser: "true"
      regions:
      - eu-central-1
